server:
  # 端口
  port: 8080
  servlet:
    # 项目路径，配置之后访问路径变成了 http://localhost:8080/demo/
    context-path: /demo

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: admin
    password: 123456